version: "3"

services:
  hapi-server:
    container_name: hapi-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    # env_file: .env
    ports:
      - "4500:4500"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - backend-challenge-network

  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    networks:
      - backend-challenge-network

networks:
  backend-challenge-network:
    driver: bridge